# Site settings
title: Vincent Knight
email: vincent.knight@gmail.com
description: "Class website for Computing for Mathematics"
baseurl: "http://drvinceknight.github.io/Computing_for_mathematics/"
url: "http://drvinceknight.github.io/Computing_for_mathematics"
github_username: "drvinceknight"
twitter_username: "@drvinceknight"
plus_username: "+VincentKnight"

# Build settings
markdown: kramdown
permalink: pretty
highlighter: pygments
